/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModsModIdRouteImport } from './routes/mods/$modId'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'

const IndexLazyRouteImport = createFileRoute('/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ModsModIdRoute = ModsModIdRouteImport.update({
  id: '/mods/$modId',
  path: '/mods/$modId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/mods/$modId': typeof ModsModIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/mods/$modId': typeof ModsModIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/mods/$modId': typeof ModsModIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/$gameId' | '/mods/$modId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/$gameId' | '/mods/$modId'
  id: '__root__' | '/' | '/games/$gameId' | '/mods/$modId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  ModsModIdRoute: typeof ModsModIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/$modId': {
      id: '/mods/$modId'
      path: '/mods/$modId'
      fullPath: '/mods/$modId'
      preLoaderRoute: typeof ModsModIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  ModsModIdRoute: ModsModIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
