export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 50,
  PAGE_SIZE_OPTIONS: [10, 25, 50] as const,
  DEFAULT_PAGE_INDEX: 0,
};

export const API = {
  DEFAULT_PAGE_SIZE: PAGINATION.DEFAULT_PAGE_SIZE,
  DEFAULT_PAGE_INDEX: PAGINATION.DEFAULT_PAGE_INDEX,
};
